### ISSUE TITLE
冰墩墩是个好作品，但是小心律师函

### ISSUE THREAD

**Issue by liuzheng** [dragonir/3d#14]
建议从本项目移除，然后用马甲

**Comment by kfcceo** [comment]
为什么小新律师函？非商业用途为啥律师函？你能解释一下嘛？

**Comment by Geek-sky** [comment]
非商业用途

**Comment by liuzheng** [comment]
第十一条违反本规则，未经许可，或者未按照许可的范围或者签署的承诺使用有关标志的，北京冬奥组委有权要求使用人纠正不当使用行为或者撤销对其许可；情节严重的，依法追究使用人的法律责任。


https://www.beijing2022.cn/rpps/UncommercialUse.htm

**Comment by kfcceo** [comment]
不知道是你眼瞎还是理解能力有问题，第一条写的明明白白，”为落实“共享办奥”理念，弘扬奥林匹克精神，鼓励社会公众积极参与冬奥会筹办工作“，这难道不是不是弘扬奥林匹克精神吗？你能不能仔细看看《北京冬奥组委涉奥知识产权及相关权益非商业使用承诺书》，你看看作者违反了承诺书的哪一条？？？建议你自行注销github账户，你这么喜欢没有问题创造问题也要抬杠，建议你去YouTube的评论区和呆蛙🐸们肛一肛~

**Comment by zzy-life** [comment]
既然兄弟们都会上github，并且会使用issues
就不要把国内论坛的评论区习气带到这里来了——啥也不知道，只会敲键盘

**Comment by 3078238359** [comment]
> 非商业用途不涉及侵权
> 
> Non-commercial use does not involve infringement

感觉你啥都不懂，你就在那边阿巴阿吧
