### ISSUE TITLE
Uncaught ReferenceError: THREE is not defined

### ISSUE THREAD

**Issue by xiaochao00** [dragonir/3d#24]
大佬好，我在一个简单的react项目里，把Olympic项目的代码试了下，刚开始页面报错 'THREE' is not defined  no-undef ；通过 npm s -S three 解决了；
然后，项目正常启动后，访问 http://localhost:3000/#/olympic,，页面是空白页面，调查控制台的时候，发现报错 Uncaught ReferenceError: THREE is not defined ，请教下大佬，是不是我的three哪里没配对呀

**Comment by dragonir** [comment]
当时做的时候，最新版的Three.js 在做雪花粒子效果时，api有点问题，所以用的旧版，你用这个试下 [https://github.com/dragonir/3d/blob/master/public/libs/three.min.js](https://github.com/dragonir/3d/blob/master/public/libs/three.min.js)

**Comment by xiaochao00** [comment]
好的，谢谢大佬，没看到在public/index.html 里面还导入了这个文件。
